CREATE TABLE IF NOT EXISTS article_embeddings (
  article_id BIGINT NOT NULL PRIMARY KEY,
  embedding VECTOR(384) NOT NULL,
  source_hash CHAR(64) NOT NULL DEFAULT '',
  model VARCHAR(128) NOT NULL DEFAULT '',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  VECTOR INDEX (embedding) DISTANCE=euclidean
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
