{
 "title": "CMS Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Log Volume by level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "logs/min" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (level) (count_over_time({service_name=\"cms\"} | json [1m]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Request rate (req/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(http_requests_total[5m]) \n",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Service Up>Down",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"cms\"}  * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(rate(http_requests_total{status=~\"4..\"}[5m])) or vector(0)\n)\n/\nsum(rate(http_requests_total[5m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Go runtime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"cms\"} ",
     "legendFormat": "Memory"
    },
    {
     "expr": "go_goroutines{job=\"cms\"}",
     "legendFormat": "Goroutine count"
    },
    {
     "expr": "rate(process_cpu_seconds_total{job=\"cms\"}[5ms])",
     "legendFormat": "Cpu core"
    }
   ]
  },
  {
   "title": "Request rate by status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by (status) (rate(http_requests_total[5m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Request latency",
   "type": "timeseries",
   "description": "How long requests take. p50 = typical, p95/p99 = the slowest requests. Rising p99 = slow tail.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(http_request_duration_seconds_bucket[5m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rate(http_request_duration_seconds_bucket[5m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(http_request_duration_seconds_bucket[5m])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Top routes",
   "type": "table",
   "description": "Where traffic concentrates\n",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(5, sum by(route) (rate(http_requests_total[5m]))) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CMS logs",
   "type": "logs",
   "description": "Main explorer, without health and metrics",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service=\"cms\"} != \"/metrics\"  "
    }
   ]
  },
  {
   "title": "Error logs",
   "type": "logs",
   "description": "All errors from 400 and above are displayed here",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service=\"cms\"} | json | status >= 400"
    }
   ]
  }
 ]
}