#!/usr/bin/env bash
set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEPLOY_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
REPO_DIR="$(cd "${DEPLOY_DIR}/.." && pwd)"

COMPOSE_FILE="${COMPOSE_FILE:-${DEPLOY_DIR}/compose.cms.yml}"
ENV_FILE="${ENV_FILE:-${DEPLOY_DIR}/cms.env}"
NGINX_ACTIVE_INCLUDE="${NGINX_ACTIVE_INCLUDE:-/etc/nginx/triangle-cms/active-upstreams.conf}"
NGINX_BIN="${NGINX_BIN:-/usr/sbin/nginx}"
PUBLIC_BASE_URL="${PUBLIC_BASE_URL:-http://127.0.0.1}"
DEPLOY_LOCK_FILE="${DEPLOY_LOCK_FILE:-/tmp/triangle-cms-deploy.lock}"
BACKEND_HEALTH_TIMEOUT="${BACKEND_HEALTH_TIMEOUT:-180}"
FRONTEND_HEALTH_TIMEOUT="${FRONTEND_HEALTH_TIMEOUT:-120}"
PUBLIC_HEALTH_TIMEOUT="${PUBLIC_HEALTH_TIMEOUT:-30}"
# Generous: this covers pulling the image and loading the ONNX model on a host
# with no GPU. Exceeding it only costs semantic search, never the deployment.
EMBEDDINGS_HEALTH_TIMEOUT="${EMBEDDINGS_HEALTH_TIMEOUT:-240}"

compose() {
	docker compose -f "${COMPOSE_FILE}" --env-file "${ENV_FILE}" "$@"
}

require_file() {
  local path="$1"
  if [[ ! -f "${path}" ]]; then
    echo "required file not found: ${path}" >&2
    exit 1
  fi
}

require_readable_file() {
	local path="$1"
	if [[ ! -f "${path}" ]]; then
		echo "required file not found: ${path}" >&2
		return 1
	fi
	if [[ ! -r "${path}" ]]; then
		echo "required file is not readable: ${path}" >&2
		return 1
	fi
}

acquire_deploy_lock() {
  exec 9>"${DEPLOY_LOCK_FILE}"
  if ! flock -n 9; then
    echo "another deployment is already running (${DEPLOY_LOCK_FILE})" >&2
    exit 1
  fi
}

validate_slot() {
  local slot="$1"
  case "${slot}" in
    blue|green) ;;
    *) echo "invalid slot: ${slot}" >&2; exit 1 ;;
  esac
}

opposite_slot() {
  local slot="$1"
  validate_slot "${slot}"
  if [[ "${slot}" == "blue" ]]; then
    echo "green"
  else
    echo "blue"
  fi
}

slot_backend_port() {
  local slot="$1"
  validate_slot "${slot}"
  if [[ "${slot}" == "blue" ]]; then
    echo "8081"
  else
    echo "8082"
  fi
}

slot_frontend_port() {
  local slot="$1"
  validate_slot "${slot}"
  if [[ "${slot}" == "blue" ]]; then
    echo "8091"
  else
    echo "8092"
  fi
}

active_slot() {
	if [[ ! -f "${NGINX_ACTIVE_INCLUDE}" ]]; then
		echo "blue"
		return
	fi
	local slot
	slot="$(sed -n 's/^set[[:space:]]\+$triangle_cms_slot[[:space:]]\+\([^;]*\);/\1/p' "${NGINX_ACTIVE_INCLUDE}" | tail -n 1)"
	slot="${slot//\'/}"
	slot="${slot//\"/}"
	if [[ "${slot}" != "blue" && "${slot}" != "green" ]]; then
		echo "invalid active slot in ${NGINX_ACTIVE_INCLUDE}: ${slot:-<missing>}" >&2
		return 1
	fi
	echo "${slot}"
}

write_include_file() {
	local slot="$1"
	local path="$2"
	validate_slot "${slot}"

	local frontend_port backend_port
	frontend_port="$(slot_frontend_port "${slot}")"
	backend_port="$(slot_backend_port "${slot}")"

	{
		echo "# Generated by triangle-cms deployment scripts. Do not edit in place."
		echo "set \$triangle_cms_slot ${slot};"
		echo "set \$triangle_cms_frontend http://127.0.0.1:${frontend_port};"
		echo "set \$triangle_cms_backend http://127.0.0.1:${backend_port};"
	} > "${path}"
}

atomic_install_file() {
	local src="$1"
	local dest="$2"
	local dest_dir tmp
	dest_dir="$(dirname "${dest}")"
	tmp="$(mktemp "${dest_dir}/triangle-cms-active-upstreams.install.XXXXXX")"
	cp -p "${src}" "${tmp}"
	mv "${tmp}" "${dest}"
}

nginx_test() {
	if [[ "${DEPLOY_TEST_MODE:-0}" == "1" && -n "${NGINX_TEST_CMD:-}" ]]; then
		bash -lc "${NGINX_TEST_CMD}"
	elif [[ -n "${NGINX_TEST_CMD:-}" || -n "${NGINX_RELOAD_CMD:-}" ]]; then
		echo "NGINX_TEST_CMD/NGINX_RELOAD_CMD are test-only; set DEPLOY_TEST_MODE=1 outside production" >&2
		return 2
	elif command -v sudo >/dev/null 2>&1; then
		sudo -n "${NGINX_BIN}" -t
	else
		"${NGINX_BIN}" -t
  fi
}

nginx_reload() {
	if [[ "${DEPLOY_TEST_MODE:-0}" == "1" && -n "${NGINX_RELOAD_CMD:-}" ]]; then
		bash -lc "${NGINX_RELOAD_CMD}"
	elif [[ -n "${NGINX_TEST_CMD:-}" || -n "${NGINX_RELOAD_CMD:-}" ]]; then
		echo "NGINX_TEST_CMD/NGINX_RELOAD_CMD are test-only; set DEPLOY_TEST_MODE=1 outside production" >&2
		return 2
	elif command -v sudo >/dev/null 2>&1; then
		sudo -n "${NGINX_BIN}" -s reload
	else
		"${NGINX_BIN}" -s reload
  fi
}

nginx_reload_privilege_available() {
	if [[ "${DEPLOY_TEST_MODE:-0}" == "1" && -n "${NGINX_RELOAD_CHECK_CMD:-}" ]]; then
		bash -lc "${NGINX_RELOAD_CHECK_CMD}"
	elif [[ -n "${NGINX_RELOAD_CHECK_CMD:-}" ]]; then
		echo "NGINX_RELOAD_CHECK_CMD is test-only; set DEPLOY_TEST_MODE=1 outside production" >&2
		return 2
	elif command -v sudo >/dev/null 2>&1; then
		sudo -n -l "${NGINX_BIN}" -s reload >/dev/null 2>&1
	else
		[[ "$(id -u)" == "0" && -x "${NGINX_BIN}" ]]
	fi
}

deployment_preflight() {
	local include_dir probe
	include_dir="$(dirname "${NGINX_ACTIVE_INCLUDE}")"

	if [[ ! -d "${include_dir}" ]]; then
		echo "deployment preflight failed: active include directory does not exist: ${include_dir}" >&2
		return 1
	fi
	if [[ ! -w "${include_dir}" ]]; then
		echo "deployment preflight failed: runner cannot write active include directory: ${include_dir}" >&2
		return 1
	fi
	if ! probe="$(mktemp "${include_dir}/.triangle-cms-preflight.XXXXXX")"; then
		echo "deployment preflight failed: runner cannot create files in active include directory: ${include_dir}" >&2
		return 1
	fi
	rm -f "${probe}"

	if [[ -e "${NGINX_ACTIVE_INCLUDE}" ]]; then
		if [[ ! -f "${NGINX_ACTIVE_INCLUDE}" ]]; then
			echo "deployment preflight failed: active include is not a regular file: ${NGINX_ACTIVE_INCLUDE}" >&2
			return 1
		fi
		if [[ ! -r "${NGINX_ACTIVE_INCLUDE}" ]]; then
			echo "deployment preflight failed: active include is not readable: ${NGINX_ACTIVE_INCLUDE}" >&2
			return 1
		fi
		if [[ ! -w "${NGINX_ACTIVE_INCLUDE}" ]]; then
			echo "deployment preflight failed: active include is not writable: ${NGINX_ACTIVE_INCLUDE}" >&2
			return 1
		fi
	fi

	if ! active_slot >/dev/null; then
		echo "deployment preflight failed: active slot value is invalid" >&2
		return 1
	fi
	if ! require_readable_file "${ENV_FILE}"; then
		echo "deployment preflight failed: cms.env is missing or unreadable: ${ENV_FILE}" >&2
		return 1
	fi
	if ! nginx_test; then
		echo "deployment preflight failed: Nginx validation is not available or failed" >&2
		return 1
	fi
	if ! nginx_reload_privilege_available; then
		echo "deployment preflight failed: Nginx reload privilege is not available for ${NGINX_BIN} -s reload" >&2
		return 1
	fi
}

http_get() {
  local url="$1"
  if command -v curl >/dev/null 2>&1; then
    curl -fsS --max-time 5 "${url}" >/dev/null
  else
    wget -q -O /dev/null --timeout=5 "${url}"
  fi
}

wait_for_url() {
  local label="$1"
  local url="$2"
  local timeout_seconds="${3:-120}"
  local deadline=$((SECONDS + timeout_seconds))

  until http_get "${url}"; do
    if (( SECONDS >= deadline )); then
      echo "timed out waiting for ${label}: ${url}" >&2
      return 1
    fi
    sleep 3
  done
}

# wait_for_embeddings polls the container's health state rather than an HTTP
# endpoint, because the sidecar is deliberately not published to the host: only
# the backends reach it, over the compose network. Its healthcheck 503s until the
# model has finished loading, so "healthy" here means it can actually answer.
wait_for_embeddings() {
	local deadline=$((SECONDS + EMBEDDINGS_HEALTH_TIMEOUT))
	local container status=""

	while true; do
		container="$(compose ps -q embeddings 2>/dev/null || true)"
		if [[ -n "${container}" ]]; then
			status="$(docker inspect -f '{{if .State.Health}}{{.State.Health.Status}}{{else}}none{{end}}' "${container}" 2>/dev/null || true)"
			if [[ "${status}" == "healthy" ]]; then
				return 0
			fi
		fi
		if (( SECONDS >= deadline )); then
			echo "timed out waiting for the embeddings sidecar (last status: ${status:-unknown})" >&2
			return 1
		fi
		sleep 3
	done
}

wait_for_slot() {
	local slot="$1"
	validate_slot "${slot}"
	wait_for_url "backend ${slot}" "http://127.0.0.1:$(slot_backend_port "${slot}")/v1/health/db" "${BACKEND_HEALTH_TIMEOUT}"
	wait_for_url "frontend ${slot}" "http://127.0.0.1:$(slot_frontend_port "${slot}")/healthz" "${FRONTEND_HEALTH_TIMEOUT}"
}

public_smoke_test() {
	local base="${PUBLIC_BASE_URL%/}"
	wait_for_url "public nginx health" "${base}/healthz" "${PUBLIC_HEALTH_TIMEOUT}"
	wait_for_url "public backend readiness" "${base}/v1/health/db" "${PUBLIC_HEALTH_TIMEOUT}"
	wait_for_url "public frontend" "${base}/" "${PUBLIC_HEALTH_TIMEOUT}"
}

transactional_switch_slot() {
	local next_slot="$1"
	validate_slot "${next_slot}"

	local current_slot include_dir tmpdir candidate prior prior_exists original_failure
	current_slot="$(active_slot)"
	validate_slot "${current_slot}"
	include_dir="$(dirname "${NGINX_ACTIVE_INCLUDE}")"
	tmpdir="$(mktemp -d "${include_dir}/triangle-cms-switch.XXXXXX")"
	candidate="${tmpdir}/candidate.conf"
	prior="${tmpdir}/prior.conf"
	prior_exists=false

	cleanup_switch_tmp() {
		trap - RETURN HUP INT TERM
		if [[ -n "${tmpdir:-}" ]]; then
			rm -rf "${tmpdir}"
		fi
	}
	trap cleanup_switch_tmp RETURN HUP INT TERM

	if [[ -f "${NGINX_ACTIVE_INCLUDE}" ]]; then
		cp -p "${NGINX_ACTIVE_INCLUDE}" "${prior}"
		prior_exists=true
	fi

	write_include_file "${next_slot}" "${candidate}"
	if [[ "${prior_exists}" == "true" ]]; then
		chmod --reference="${prior}" "${candidate}"
	else
		chmod 0644 "${candidate}"
	fi

	restore_prior_include() {
		local cause="$1"
		echo "restoring previous Nginx include after failed switch to ${next_slot}: ${cause}" >&2
		if [[ "${prior_exists}" == "true" ]]; then
			if ! atomic_install_file "${prior}" "${NGINX_ACTIVE_INCLUDE}"; then
				echo "CRITICAL: failed to restore previous Nginx include after: ${cause}" >&2
				return 1
			fi
		else
			if ! rm -f "${NGINX_ACTIVE_INCLUDE}"; then
				echo "CRITICAL: failed to remove failed candidate include after: ${cause}" >&2
				return 1
			fi
		fi
	}

	atomic_install_file "${candidate}" "${NGINX_ACTIVE_INCLUDE}"
	if ! nginx_test; then
		original_failure="nginx validation failed after installing candidate include for ${next_slot}"
		if ! restore_prior_include "${original_failure}"; then
			echo "CRITICAL: ${original_failure}; restoration also failed and operator intervention is required" >&2
			return 10
		fi
		echo "${original_failure}; previous include restored" >&2
		return 1
	fi

	if ! nginx_reload; then
		original_failure="nginx reload failed after validation for ${next_slot}"
		if ! restore_prior_include "${original_failure}"; then
			echo "CRITICAL: ${original_failure}; restoration also failed and operator intervention is required" >&2
			return 10
		fi
		if ! nginx_test; then
			echo "CRITICAL: ${original_failure}; restored include failed nginx validation and operator intervention is required" >&2
			return 11
		fi
		if ! nginx_reload; then
			echo "CRITICAL: ${original_failure}; restored include validation passed but recovery reload failed and operator intervention is required" >&2
			return 12
		fi
		echo "${original_failure}; previous include restored and reloaded" >&2
		return 1
	fi

	return 0
}
